### PR TITLE
Restores velocities after recreating physics state

### PR DESCRIPTION
**Pull request by eddieataberk**

### CODE REVIEW

**Comment by Moddingear** [comment]
Can you add a way to enable and disable this ? Some people might not want this.
Something like KeepMomentumOnCollisionUpdate

**Comment by eddieataberk** [comment]
> Can you add a way to enable and disable this ? Some people might not want this.
> Something like KeepMomentumOnCollisionUpdate

Done :)

**Comment by Alex-Folts** [comment]
Maybe make default false to preserve current behavior by default?

**Comment by eddieataberk** [comment]
> Maybe make default false to preserve current behavior by default?

Sure.

**Comment by Moddingear** [comment]
Usually there's a getter/setter for things like this but I think in this case this is fine as it's only used in this one function, so it's a merge.

**Pull request merged**
